apiVersion: v1
kind: Secret
metadata:
  name: doctor-service-secret
  namespace: default
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "production_secure_db_password"
  JWT_SECRET: "production_super_secret_jwt_key_change_in_cloud"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
